/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-04-08 06:17:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class ForgotPassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Password Recovery | HealthCare Appointment System</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary-color: #3b82f6;\n");
      out.write("            --primary-dark: #2563eb;\n");
      out.write("            --secondary-color: #60a5fa;\n");
      out.write("            --accent-color: #93c5fd;\n");
      out.write("            --light-gray: #f8fafc;\n");
      out.write("            --dark-gray: #64748b;\n");
      out.write("            --danger-color: #ef4444;\n");
      out.write("            --success-color: #10b981;\n");
      out.write("            --shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n");
      out.write("            --transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n");
      out.write("            --border-radius: 12px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            background-color: #f1f5f9;\n");
      out.write("            color: #1e293b;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .navbar {\n");
      out.write("            background-color: var(--secondary-color);\n");
      out.write("            color: white;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 15px 5%;\n");
      out.write("            box-shadow: 0 4px 12px rgba(0,0,0,0.1);\n");
      out.write("            position: sticky;\n");
      out.write("            top: 0;\n");
      out.write("            z-index: 1000;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-container {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: transform 0.3s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-container:hover {\n");
      out.write("            transform: scale(1.05);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo {\n");
      out.write("            width: 45px;\n");
      out.write("            height: 45px;\n");
      out.write("            margin-right: 12px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            object-fit: cover;\n");
      out.write("            border: 2px solid var(--light-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-name {\n");
      out.write("            font-size: 22px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-name span {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-links {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 15px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-btn {\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 16px;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border-radius: 30px;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            font-weight: 600;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-btn i {\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .admin-btn {\n");
      out.write("            background-color: var(--accent-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .doctor-btn {\n");
      out.write("            background-color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .user-btn {\n");
      out.write("            background-color: var(--success-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-btn:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .recovery-wrapper {\n");
      out.write("            display: flex;\n");
      out.write("            min-height: calc(100vh - 72px);\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 2rem;\n");
      out.write("            background: url('images/recovery-bg.jpg') no-repeat center center;\n");
      out.write("            background-size: cover;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .recovery-wrapper::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background: rgba(59, 130, 246, 0.88);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .recovery-container {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 500px;\n");
      out.write("            padding: 2.5rem;\n");
      out.write("            background: white;\n");
      out.write("            border-radius: var(--border-radius);\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.15);\n");
      out.write("            position: relative;\n");
      out.write("            z-index: 1;\n");
      out.write("            transform: translateY(0);\n");
      out.write("            transition: var(--transition);\n");
      out.write("            border: 1px solid rgba(255,255,255,0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .recovery-container:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 15px 35px rgba(0,0,0,0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .recovery-header {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .recovery-header h2 {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .recovery-header p {\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .user-type-badge {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 0.3rem 1rem;\n");
      out.write("            background-color: rgba(59, 130, 246, 0.1);\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            border-radius: 50px;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .security-icon {\n");
      out.write("            font-size: 2.5rem;\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 0.6rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group input, .form-group select {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.9rem 1rem 0.9rem 3.2rem;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            border-radius: var(--border-radius);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            transition: var(--transition);\n");
      out.write("            background-color: #f8fafc;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group input:focus, .form-group select:focus {\n");
      out.write("            border-color: var(--accent-color);\n");
      out.write("            box-shadow: 0 0 0 3px rgba(96, 165, 250, 0.3);\n");
      out.write("            outline: none;\n");
      out.write("            background-color: white;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .input-icon {\n");
      out.write("            position: absolute;\n");
      out.write("            left: 1rem;\n");
      out.write("            top: 2.7rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .reset-btn {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 1rem;\n");
      out.write("            background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: var(--border-radius);\n");
      out.write("            font-size: 1rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: var(--transition);\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            box-shadow: var(--shadow);\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .reset-btn:hover {\n");
      out.write("            background: linear-gradient(135deg, var(--primary-dark), var(--secondary-color));\n");
      out.write("            box-shadow: 0 6px 12px rgba(59, 130, 246, 0.25);\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .back-to-login {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 1.8rem;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .back-to-login a {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: var(--transition);\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.3rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .back-to-login a:hover {\n");
      out.write("            color: var(--secondary-color);\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .message {\n");
      out.write("            padding: 0.9rem 1rem;\n");
      out.write("            margin-bottom: 1.8rem;\n");
      out.write("            border-radius: var(--border-radius);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            text-align: center;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 0.6rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .success {\n");
      out.write("            background-color: rgba(16, 185, 129, 0.1);\n");
      out.write("            color: var(--success-color);\n");
      out.write("            border: 1px solid rgba(16, 185, 129, 0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error {\n");
      out.write("            background-color: rgba(239, 68, 68, 0.1);\n");
      out.write("            color: var(--danger-color);\n");
      out.write("            border: 1px solid rgba(239, 68, 68, 0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .password-hint {\n");
      out.write("            margin-top: 0.5rem;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.3rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .navbar {\n");
      out.write("                padding: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-links {\n");
      out.write("                gap: 0.8rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .recovery-container {\n");
      out.write("                padding: 1.8rem;\n");
      out.write("                margin: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .recovery-header h2 {\n");
      out.write("                font-size: 1.7rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <nav class=\"navbar\">\n");
      out.write("        <div class=\"logo-container\" onclick=\"window.location.href='../index.jsp'\">\n");
      out.write("            <img src=\"../images/1.avif\" alt=\"Logo\" class=\"logo\">\n");
      out.write("            <span class=\"logo-name\">Health<span>Care</span></span>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"nav-links\">\n");
      out.write("            <a href=\"AdminLogin.jsp\" class=\"nav-btn admin-btn\">\n");
      out.write("                <i class=\"fas fa-user-shield\"></i> ADMIN\n");
      out.write("            </a>\n");
      out.write("            <a href=\"DoctorLogin.jsp\" class=\"nav-btn doctor-btn\">\n");
      out.write("                <i class=\"fas fa-user-md\"></i> DOCTOR\n");
      out.write("            </a>\n");
      out.write("            <a href=\"UserLogin.jsp\" class=\"nav-btn user-btn\">\n");
      out.write("                <i class=\"fas fa-user\"></i> USER\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("    \n");
      out.write("    <div class=\"recovery-wrapper\">\n");
      out.write("        <div class=\"recovery-container\">\n");
      out.write("            <div class=\"recovery-header\">\n");
      out.write("                <div class=\"security-icon\">\n");
      out.write("                    <i class=\"fas fa-key\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h2>Password Recovery</h2>\n");
      out.write("                <p>Reset your account password securely</p>\n");
      out.write("                \n");
      out.write("                ");

                    String type = request.getParameter("type");
                    String userType = "";
                    String actionUrl = "";
                    String loginPage = "UserLogin.jsp";

                    if ("Admin".equals(type)) {
                        userType = "Admin Account";
                        actionUrl = "AdminForgotPasswordServlet";
                        loginPage = "AdminLogin.jsp";
                    } else if ("Doctor".equals(type)) {
                        userType = "Doctor Account";
                        actionUrl = "DoctorForgotPasswordServlet";
                        loginPage = "DoctorLogin.jsp";
                    } else {
                        userType = "User Account";
                        actionUrl = "UserForgotPasswordServlet";
                        loginPage = "UserLogin.jsp";
                    }
                
      out.write("\n");
      out.write("                <div class=\"user-type-badge\">\n");
      out.write("                    <i class=\"fas fa-user-tag\"></i> ");
      out.print( userType );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");

                String message = (String) request.getAttribute("message");
                String messageClass = (String) request.getAttribute("messageClass");
                if (message != null) {
            
      out.write("\n");
      out.write("                <div class=\"message ");
      out.print( messageClass );
      out.write("\">\n");
      out.write("                    <i class=\"fas fa-");
      out.print( "success".equals(messageClass) ? "check-circle" : "exclamation-circle" );
      out.write("\"></i>\n");
      out.write("                    ");
      out.print( message );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <form action=\"");
      out.print( actionUrl );
      out.write("\" method=\"post\">\n");
      out.write("                <input type=\"hidden\" name=\"type\" value=\"");
      out.print( type );
      out.write("\">\n");
      out.write("                \n");
      out.write("                ");
 if ("User".equals(type)) { 
      out.write("\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"email\">Email Address</label>\n");
      out.write("                        <div class=\"input-icon\">\n");
      out.write("                            <i class=\"fas fa-envelope\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Enter your registered email\" required>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"username\">Username</label>\n");
      out.write("                        <div class=\"input-icon\">\n");
      out.write("                            <i class=\"fas fa-user\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Enter your username\" required>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"securityQuestion\">Security Question</label>\n");
      out.write("                    <div class=\"input-icon\">\n");
      out.write("                        <i class=\"fas fa-shield-alt\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <select id=\"securityQuestion\" name=\"securityQuestion\" required>\n");
      out.write("                        <option value=\"\">Select a security question</option>\n");
      out.write("                        <option value=\"What was your first pet's name?\">What was your first pet's name?</option>\n");
      out.write("                        <option value=\"What city were you born in?\">What city were you born in?</option>\n");
      out.write("                        <option value=\"What is your mother's maiden name?\">What is your mother's maiden name?</option>\n");
      out.write("                        <option value=\"What was the name of your first school?\">What was the name of your first school?</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"securityAnswer\">Security Answer</label>\n");
      out.write("                    <div class=\"input-icon\">\n");
      out.write("                        <i class=\"fas fa-lock\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"text\" id=\"securityAnswer\" name=\"securityAnswer\" placeholder=\"Enter your answer\" required>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"newPassword\">New Password</label>\n");
      out.write("                    <div class=\"input-icon\">\n");
      out.write("                        <i class=\"fas fa-lock\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"password\" id=\"newPassword\" name=\"newPassword\" placeholder=\"Create a new password\" required>\n");
      out.write("                    <div class=\"password-hint\">\n");
      out.write("                        <i class=\"fas fa-info-circle\"></i>\n");
      out.write("                        Minimum 8 characters with numbers and symbols\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"confirmPassword\">Confirm New Password</label>\n");
      out.write("                    <div class=\"input-icon\">\n");
      out.write("                        <i class=\"fas fa-lock\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" placeholder=\"Confirm your new password\" required>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"reset-btn\">\n");
      out.write("                    <i class=\"fas fa-sync-alt\"></i> Reset Password\n");
      out.write("                </button>\n");
      out.write("                \n");
      out.write("                <div class=\"back-to-login\">\n");
      out.write("                    <a href=\"");
      out.print( loginPage );
      out.write("\"><i class=\"fas fa-arrow-left\"></i> Back to Login</a>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
