/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-04-12 14:26:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class UserRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Patient Registration | HealthCare Appointment System</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary-color: #3b82f6;\n");
      out.write("            --primary-dark: #2563eb;\n");
      out.write("            --secondary-color: #60a5fa;\n");
      out.write("            --accent-color: #93c5fd;\n");
      out.write("            --light-gray: #f8fafc;\n");
      out.write("            --dark-gray: #64748b;\n");
      out.write("            --danger-color: #ef4444;\n");
      out.write("            --success-color: #10b981;\n");
      out.write("            --shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n");
      out.write("            --transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n");
      out.write("            --border-radius: 12px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            background-color: #f1f5f9;\n");
      out.write("            color: #1e293b;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .navbar {\n");
      out.write("            background-color: var(--secondary-color);\n");
      out.write("            color: white;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 15px 5%;\n");
      out.write("            box-shadow: 0 4px 12px rgba(0,0,0,0.1);\n");
      out.write("            position: sticky;\n");
      out.write("            top: 0;\n");
      out.write("            z-index: 1000;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-container {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: transform 0.3s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-container:hover {\n");
      out.write("            transform: scale(1.05);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo {\n");
      out.write("            width: 45px;\n");
      out.write("            height: 45px;\n");
      out.write("            margin-right: 12px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            object-fit: cover;\n");
      out.write("            border: 2px solid var(--light-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-name {\n");
      out.write("            font-size: 22px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-name span {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-links {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 15px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-btn {\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 16px;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border-radius: 30px;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            font-weight: 600;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-btn i {\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .admin-btn {\n");
      out.write("            background-color: var(--accent-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .doctor-btn {\n");
      out.write("            background-color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .user-btn {\n");
      out.write("            background-color: var(--success-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-btn:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-wrapper {\n");
      out.write("            display: flex;\n");
      out.write("            min-height: calc(100vh - 72px);\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 2rem;\n");
      out.write("            background: url('images/patient-register-bg.jpg') no-repeat center center;\n");
      out.write("            background-size: cover;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-wrapper::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background: rgba(59, 130, 246, 0.88);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-container {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 600px;\n");
      out.write("            padding: 2.5rem;\n");
      out.write("            background: white;\n");
      out.write("            border-radius: var(--border-radius);\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.15);\n");
      out.write("            position: relative;\n");
      out.write("            z-index: 1;\n");
      out.write("            transform: translateY(0);\n");
      out.write("            transition: var(--transition);\n");
      out.write("            border: 1px solid rgba(255,255,255,0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-container:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 15px 35px rgba(0,0,0,0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-header {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 2.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-header h2 {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            font-size: 2rem;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-header p {\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: 400;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .patient-icon {\n");
      out.write("            font-size: 2.8rem;\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            margin-bottom: 1.2rem;\n");
      out.write("            background: rgba(59, 130, 246, 0.1);\n");
      out.write("            width: 80px;\n");
      out.write("            height: 80px;\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            border-radius: 50%;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 0.6rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group input, .form-group select {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.9rem 1rem 0.9rem 3.2rem;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            border-radius: var(--border-radius);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            transition: var(--transition);\n");
      out.write("            background-color: #f8fafc;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group input:focus, .form-group select:focus {\n");
      out.write("            border-color: var(--accent-color);\n");
      out.write("            box-shadow: 0 0 0 3px rgba(96, 165, 250, 0.3);\n");
      out.write("            outline: none;\n");
      out.write("            background-color: white;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .input-icon {\n");
      out.write("            position: absolute;\n");
      out.write("            left: 1rem;\n");
      out.write("            top: 2.7rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-row {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-row .form-group {\n");
      out.write("            flex: 1;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-btn {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 1rem;\n");
      out.write("            background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: var(--border-radius);\n");
      out.write("            font-size: 1rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: var(--transition);\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            box-shadow: var(--shadow);\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-btn:hover {\n");
      out.write("            background: linear-gradient(135deg, var(--primary-dark), var(--secondary-color));\n");
      out.write("            box-shadow: 0 6px 12px rgba(59, 130, 246, 0.25);\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .login-link {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 1.8rem;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .login-link a {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: var(--transition);\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.3rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .login-link a:hover {\n");
      out.write("            color: var(--secondary-color);\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-message {\n");
      out.write("            color: var(--danger-color);\n");
      out.write("            margin-top: 0.5rem;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.3rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .password-hint {\n");
      out.write("            margin-top: 0.5rem;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.3rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-dropdown {\n");
      out.write("            margin-bottom: 1.8rem;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-dropdown label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 0.6rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .dropdown-select {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.9rem 1rem 0.9rem 3.2rem;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            border-radius: var(--border-radius);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            transition: var(--transition);\n");
      out.write("            background-color: #f8fafc;\n");
      out.write("            appearance: none;\n");
      out.write("            -webkit-appearance: none;\n");
      out.write("            -moz-appearance: none;\n");
      out.write("            background-image: url(\"data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6 9 12 15 18 9'%3e%3c/polyline%3e%3c/svg%3e\");\n");
      out.write("            background-repeat: no-repeat;\n");
      out.write("            background-position: right 1rem center;\n");
      out.write("            background-size: 1em;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .dropdown-select:focus {\n");
      out.write("            border-color: var(--accent-color);\n");
      out.write("            box-shadow: 0 0 0 3px rgba(96, 165, 250, 0.3);\n");
      out.write("            outline: none;\n");
      out.write("            background-color: white;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .dropdown-icon {\n");
      out.write("            position: absolute;\n");
      out.write("            left: 1rem;\n");
      out.write("            top: 2.7rem;\n");
      out.write("            color: var(--dark-gray);\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-field {\n");
      out.write("            border-color: var(--danger-color) !important;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .navbar {\n");
      out.write("                padding: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .logo-name {\n");
      out.write("                font-size: 1.3rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-links {\n");
      out.write("                gap: 0.8rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-links a {\n");
      out.write("                padding: 0.5rem 0.8rem;\n");
      out.write("                font-size: 0.85rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .register-container {\n");
      out.write("                padding: 1.8rem;\n");
      out.write("                margin: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .register-header h2 {\n");
      out.write("                font-size: 1.7rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .form-row {\n");
      out.write("                flex-direction: column;\n");
      out.write("                gap: 0;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("   <nav class=\"navbar\">\n");
      out.write("        <div class=\"logo-container\" onclick=\"window.location.href='../index.jsp'\">\n");
      out.write("            <img src=\"../images/1.avif\" alt=\"Logo\" class=\"logo\">\n");
      out.write("            <span class=\"logo-name\">Health<span>Care</span></span>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"nav-links\">\n");
      out.write("            <a href=\"AdminLogin.jsp\" class=\"nav-btn admin-btn\">\n");
      out.write("                <i class=\"fas fa-user-shield\"></i> ADMIN\n");
      out.write("            </a>\n");
      out.write("            <a href=\"DoctorLogin.jsp\" class=\"nav-btn doctor-btn\">\n");
      out.write("                <i class=\"fas fa-user-md\"></i> DOCTOR\n");
      out.write("            </a>\n");
      out.write("            <a href=\"UserLogin.jsp\" class=\"nav-btn user-btn\">\n");
      out.write("                <i class=\"fas fa-user\"></i> USER\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("    \n");
      out.write("    <div class=\"register-wrapper\">\n");
      out.write("        <div class=\"register-container\">\n");
      out.write("            <div class=\"register-header\">\n");
      out.write("                <div class=\"patient-icon\">\n");
      out.write("                    <i class=\"fas fa-user-plus\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h2>Patient Registration</h2>\n");
      out.write("                <p>Create your account to access healthcare services</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 if(request.getAttribute("errorMessage") != null) { 
      out.write("\n");
      out.write("                <div class=\"error-message\" style=\"margin-bottom: 1.5rem;\">\n");
      out.write("                    <i class=\"fas fa-exclamation-circle\"></i>\n");
      out.write("                    ");
      out.print( request.getAttribute("errorMessage") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <form action=\"UserRegisterServlet\" method=\"post\">\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"firstName\">Full Name</label>\n");
      out.write("                        <div class=\"input-icon\">\n");
      out.write("                            <i class=\"fas fa-user\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <input type=\"text\" id=\"firstName\" name=\"firstName\" \n");
      out.write("                               value=\"");
      out.print( request.getParameter("firstName") != null ? request.getParameter("firstName") : "" );
      out.write("\" \n");
      out.write("                               required\n");
      out.write("                               class=\"");
      out.print( "firstName".equals(request.getAttribute("errorField")) ? "error-field" : "" );
      out.write("\">\n");
      out.write("                        ");
 if("firstName".equals(request.getAttribute("errorField"))) { 
      out.write("\n");
      out.write("                            <div class=\"error-message\">\n");
      out.write("                                <i class=\"fas fa-exclamation-circle\"></i>\n");
      out.write("                                ");
      out.print( request.getAttribute("fieldErrorMessage") );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"email\">Email Address</label>\n");
      out.write("                    <div class=\"input-icon\">\n");
      out.write("                        <i class=\"fas fa-envelope\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" \n");
      out.write("                           value=\"");
      out.print( request.getParameter("email") != null ? request.getParameter("email") : "" );
      out.write("\" \n");
      out.write("                           required\n");
      out.write("                           class=\"");
      out.print( "email".equals(request.getAttribute("errorField")) ? "error-field" : "" );
      out.write("\">\n");
      out.write("                    ");
 if("email".equals(request.getAttribute("errorField"))) { 
      out.write("\n");
      out.write("                        <div class=\"error-message\">\n");
      out.write("                            <i class=\"fas fa-exclamation-circle\"></i>\n");
      out.write("                            ");
      out.print( request.getAttribute("fieldErrorMessage") );
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"password\">Password</label>\n");
      out.write("                        <div class=\"input-icon\">\n");
      out.write("                            <i class=\"fas fa-lock\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"password\" \n");
      out.write("                               required\n");
      out.write("                               pattern=\"(?=.*\\d)(?=.*[!@#$%^&*]).{8,}\"\n");
      out.write("                               title=\"Password must be at least 8 characters long and contain at least one number and one special character\"\n");
      out.write("                               class=\"");
      out.print( "password".equals(request.getAttribute("errorField")) ? "error-field" : "" );
      out.write("\">\n");
      out.write("                        <div class=\"password-hint\">\n");
      out.write("                            <i class=\"fas fa-info-circle\"></i>\n");
      out.write("                            Use at least 8 characters with numbers and symbols\n");
      out.write("                        </div>\n");
      out.write("                        ");
 if("password".equals(request.getAttribute("errorField"))) { 
      out.write("\n");
      out.write("                            <div class=\"error-message\">\n");
      out.write("                                <i class=\"fas fa-exclamation-circle\"></i>\n");
      out.write("                                ");
      out.print( request.getAttribute("fieldErrorMessage") );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"confirmPassword\">Confirm Password</label>\n");
      out.write("                        <div class=\"input-icon\">\n");
      out.write("                            <i class=\"fas fa-lock\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" \n");
      out.write("                               required\n");
      out.write("                               class=\"");
      out.print( "confirmPassword".equals(request.getAttribute("errorField")) ? "error-field" : "" );
      out.write("\">\n");
      out.write("                        ");
 if("confirmPassword".equals(request.getAttribute("errorField"))) { 
      out.write("\n");
      out.write("                            <div class=\"error-message\">\n");
      out.write("                                <i class=\"fas fa-exclamation-circle\"></i>\n");
      out.write("                                ");
      out.print( request.getAttribute("fieldErrorMessage") );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"phone\">Phone Number</label>\n");
      out.write("                    <div class=\"input-icon\">\n");
      out.write("                        <i class=\"fas fa-phone\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"tel\" id=\"phone\" name=\"phone\" \n");
      out.write("                           value=\"");
      out.print( request.getParameter("phone") != null ? request.getParameter("phone") : "" );
      out.write("\" \n");
      out.write("                           required\n");
      out.write("                           pattern=\"[0-9]{10}\"\n");
      out.write("                           title=\"Please enter a 10-digit phone number\"\n");
      out.write("                           class=\"");
      out.print( "phone".equals(request.getAttribute("errorField")) ? "error-field" : "" );
      out.write("\">\n");
      out.write("                    ");
 if("phone".equals(request.getAttribute("errorField"))) { 
      out.write("\n");
      out.write("                        <div class=\"error-message\">\n");
      out.write("                            <i class=\"fas fa-exclamation-circle\"></i>\n");
      out.write("                            ");
      out.print( request.getAttribute("fieldErrorMessage") );
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-dropdown\">\n");
      out.write("                    <label for=\"user-type\">User Type</label>\n");
      out.write("                    <div class=\"dropdown-icon\">\n");
      out.write("                        <i class=\"fas fa-users\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <select id=\"user-type\" name=\"user\" class=\"dropdown-select\" required>\n");
      out.write("                        <option value=\"\" disabled selected>Select user type</option>\n");
      out.write("                        <option value=\"user\" ");
      out.print( "user".equals(request.getParameter("user")) ? "selected" : "" );
      out.write(">User</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"register-btn\">\n");
      out.write("                    <i class=\"fas fa-user-plus\"></i> Create Account\n");
      out.write("                </button>\n");
      out.write("                \n");
      out.write("                <div class=\"login-link\">\n");
      out.write("                    <p>Already have an account? <a href=\"UserLogin.jsp\"><i class=\"fas fa-sign-in-alt\"></i> Login here</a></p>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
