/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-04-07 07:50:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>HealthCare Appointment System</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary-color: #3498db;\n");
      out.write("            --secondary-color: #2c3e50;\n");
      out.write("            --accent-color: #e74c3c;\n");
      out.write("            --light-color: #ecf0f1;\n");
      out.write("            --dark-color: #2c3e50;\n");
      out.write("            --success-color: #2ecc71;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            background-color: #f9f9f9;\n");
      out.write("            color: #333;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .navbar {\n");
      out.write("            background-color: var(--secondary-color);\n");
      out.write("            color: white;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 15px 5%;\n");
      out.write("            box-shadow: 0 4px 12px rgba(0,0,0,0.1);\n");
      out.write("            position: sticky;\n");
      out.write("            top: 0;\n");
      out.write("            z-index: 1000;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-container {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: transform 0.3s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-container:hover {\n");
      out.write("            transform: scale(1.05);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo {\n");
      out.write("            width: 45px;\n");
      out.write("            height: 45px;\n");
      out.write("            margin-right: 12px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            object-fit: cover;\n");
      out.write("            border: 2px solid var(--light-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-name {\n");
      out.write("            font-size: 22px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo-name span {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-links {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 15px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-btn {\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 16px;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border-radius: 30px;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            font-weight: 600;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-btn i {\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .admin-btn {\n");
      out.write("            background-color: var(--accent-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .doctor-btn {\n");
      out.write("            background-color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .user-btn {\n");
      out.write("            background-color: var(--success-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-btn:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            padding: 80px 5%;\n");
      out.write("            background: linear-gradient(135deg, #f5f7fa 0%, #e4e8eb 100%);\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: -50%;\n");
      out.write("            right: -50%;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 200%;\n");
      out.write("            background: radial-gradient(circle, rgba(52, 152, 219, 0.1) 0%, rgba(0,0,0,0) 70%);\n");
      out.write("            z-index: 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-content {\n");
      out.write("            flex: 1;\n");
      out.write("            max-width: 600px;\n");
      out.write("            z-index: 1;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-content h1 {\n");
      out.write("            font-size: 42px;\n");
      out.write("            color: var(--dark-color);\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            line-height: 1.2;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-content h1 span {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-content p {\n");
      out.write("            color: #555;\n");
      out.write("            font-size: 18px;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .cta-buttons {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 15px;\n");
      out.write("            margin-top: 30px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .cta-btn {\n");
      out.write("            padding: 12px 25px;\n");
      out.write("            border-radius: 30px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .primary-btn {\n");
      out.write("            background-color: var(--primary-color);\n");
      out.write("            color: white;\n");
      out.write("            box-shadow: 0 4px 15px rgba(52, 152, 219, 0.3);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .secondary-btn {\n");
      out.write("            background-color: white;\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            border: 2px solid var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .cta-btn:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            box-shadow: 0 8px 20px rgba(0,0,0,0.15);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .primary-btn:hover {\n");
      out.write("            background-color: #2980b9;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .secondary-btn:hover {\n");
      out.write("            background-color: var(--primary-color);\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-image {\n");
      out.write("            flex: 1;\n");
      out.write("            max-width: 500px;\n");
      out.write("            z-index: 1;\n");
      out.write("            animation: float 6s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-image img {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 500px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 25px 50px -12px rgba(0,0,0,0.25);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        @keyframes float {\n");
      out.write("            0% { transform: translateY(0px); }\n");
      out.write("            50% { transform: translateY(-20px); }\n");
      out.write("            100% { transform: translateY(0px); }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .features {\n");
      out.write("            padding: 80px 5%;\n");
      out.write("            background-color: white;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .section-title {\n");
      out.write("            font-size: 36px;\n");
      out.write("            color: var(--dark-color);\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .section-subtitle {\n");
      out.write("            color: #777;\n");
      out.write("            font-size: 18px;\n");
      out.write("            max-width: 700px;\n");
      out.write("            margin: 0 auto 50px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .features-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n");
      out.write("            gap: 30px;\n");
      out.write("            margin-top: 50px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-card {\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            padding: 30px;\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.05);\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\n");
      out.write("            border: 1px solid #eee;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-card:hover {\n");
      out.write("            transform: translateY(-10px);\n");
      out.write("            box-shadow: 0 15px 30px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-icon {\n");
      out.write("            width: 70px;\n");
      out.write("            height: 70px;\n");
      out.write("            background-color: rgba(52, 152, 219, 0.1);\n");
      out.write("            border-radius: 50%;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin: 0 auto 20px;\n");
      out.write("            color: var(--primary-color);\n");
      out.write("            font-size: 30px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-title {\n");
      out.write("            font-size: 22px;\n");
      out.write("            color: var(--dark-color);\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .feature-desc {\n");
      out.write("            color: #666;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        footer {\n");
      out.write("            background-color: var(--secondary-color);\n");
      out.write("            color: white;\n");
      out.write("            padding: 40px 5%;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .footer-content {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .footer-logo {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .footer-logo img {\n");
      out.write("            width: 50px;\n");
      out.write("            height: 50px;\n");
      out.write("            margin-right: 15px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .footer-logo span {\n");
      out.write("            font-size: 24px;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .footer-links {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 20px;\n");
      out.write("            margin: 20px 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .footer-links a {\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: color 0.3s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .footer-links a:hover {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .social-icons {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 20px;\n");
      out.write("            margin: 20px 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .social-icons a {\n");
      out.write("            color: white;\n");
      out.write("            font-size: 20px;\n");
      out.write("            transition: color 0.3s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .social-icons a:hover {\n");
      out.write("            color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .copyright {\n");
      out.write("            margin-top: 30px;\n");
      out.write("            color: rgba(255,255,255,0.7);\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .navbar {\n");
      out.write("                flex-direction: column;\n");
      out.write("                padding: 15px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-links {\n");
      out.write("                margin-top: 15px;\n");
      out.write("                flex-wrap: wrap;\n");
      out.write("                justify-content: center;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .hero {\n");
      out.write("                flex-direction: column;\n");
      out.write("                text-align: center;\n");
      out.write("                padding: 50px 5%;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .hero-content {\n");
      out.write("                margin-bottom: 40px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .cta-buttons {\n");
      out.write("                justify-content: center;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <nav class=\"navbar\">\n");
      out.write("        <div class=\"logo-container\" onclick=\"window.location.href='index.jsp'\">\n");
      out.write("            <img src=\"images/1.avif\" alt=\"Logo\" class=\"logo\">\n");
      out.write("            <span class=\"logo-name\">Health<span>Care</span></span>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"nav-links\">\n");
      out.write("            <a href=\"view/AdminLogin.jsp\" class=\"nav-btn admin-btn\">\n");
      out.write("                <i class=\"fas fa-user-shield\"></i> ADMIN\n");
      out.write("            </a>\n");
      out.write("            <a href=\"view/DoctorLogin.jsp\" class=\"nav-btn doctor-btn\">\n");
      out.write("                <i class=\"fas fa-user-md\"></i> DOCTOR\n");
      out.write("            </a>\n");
      out.write("            <a href=\"view/UserLogin.jsp\" class=\"nav-btn user-btn\">\n");
      out.write("                <i class=\"fas fa-user\"></i> USER\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("    \n");
      out.write("    <section class=\"hero\">\n");
      out.write("        <div class=\"hero-content\">\n");
      out.write("            <h1>Your Health, Our <span>Priority</span></h1>\n");
      out.write("            <p>Book appointments with top healthcare professionals effortlessly. Our system provides seamless access to doctors, quick appointment scheduling, and personalized healthcare solutions.</p>\n");
      out.write("            \n");
      out.write("            <div class=\"cta-buttons\">\n");
      out.write("                <a href=\"view/UserLogin.jsp\" class=\"cta-btn primary-btn\">\n");
      out.write("                    <i class=\"fas fa-calendar-check\"></i> Book Appointment\n");
      out.write("                </a>\n");
      out.write("                <a href=\"#features\" class=\"cta-btn secondary-btn\">\n");
      out.write("                    <i class=\"fas fa-info-circle\"></i> Learn More\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"hero-image\">\n");
      out.write("            <img src=\"images/a.avif\" alt=\"Healthcare professionals\" width=\"200\" height=\"200\">\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("    <section class=\"features\" id=\"features\">\n");
      out.write("        <h2 class=\"section-title\">Why Choose Our System</h2>\n");
      out.write("        <p class=\"section-subtitle\">We provide comprehensive healthcare solutions tailored to your needs</p>\n");
      out.write("        \n");
      out.write("        <div class=\"features-grid\">\n");
      out.write("            <div class=\"feature-card\">\n");
      out.write("                <div class=\"feature-icon\">\n");
      out.write("                    <i class=\"fas fa-clock\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"feature-title\">24/7 Availability</h3>\n");
      out.write("                <p class=\"feature-desc\">Book appointments anytime, anywhere with our round-the-clock scheduling system.</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"feature-card\">\n");
      out.write("                <div class=\"feature-icon\">\n");
      out.write("                    <i class=\"fas fa-search\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"feature-title\">Find Best Doctors</h3>\n");
      out.write("                <p class=\"feature-desc\">Access to a network of qualified and experienced healthcare professionals.</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"feature-card\">\n");
      out.write("                <div class=\"feature-icon\">\n");
      out.write("                    <i class=\"fas fa-bell\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"feature-title\">Smart Reminders</h3>\n");
      out.write("                <p class=\"feature-desc\">Never miss an appointment with our automated reminder system.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("    <footer>\n");
      out.write("        <div class=\"footer-content\">\n");
      out.write("            <div class=\"footer-logo\">\n");
      out.write("                <img src=\"images/a.avif\" alt=\"Logo\">\n");
      out.write("                <span>HealthCare</span>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"footer-links\">\n");
      out.write("                <a href=\"#\">About Us</a>\n");
      out.write("                <a href=\"#\">Services</a>\n");
      out.write("                <a href=\"#\">Doctors</a>\n");
      out.write("                <a href=\"#\">Contact</a>\n");
      out.write("                <a href=\"#\">Privacy Policy</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"social-icons\">\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <p class=\"copyright\">&copy; 2023 HealthCare Appointment System. All rights reserved.</p>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
